// ui-svelte/src/routes/(authenticated)/renders/new/NestedTextureHeader.svelte
<script lang="ts">
	import { Heading } from 'flowbite-svelte';
	import Separator from '$lib/Separator.svelte';
	import { getContext } from 'svelte';
	import { getTextureData } from '$lib/utils/render/texture';
	import type { RenderConfigContext } from './utils';

	type Props = {
		textureName: string;
	};

	const { textureName }: Props = $props();

	const renderConfigContext = getContext<RenderConfigContext>('renderConfig');

	const { data } = $derived(
		getTextureData(renderConfigContext.get(), textureName)
	);
	const { type: textureType } = $derived(data);
</script>

<div class="flex justify-between">
	<Heading tag="h2" class="text-lg font-bold italic">Contained Texture</Heading>
	<div class="flex gap-2">
		<Heading tag="h3" class="text-lg font-light not-italic">
			{textureName}
		</Heading>
		<Separator vertical />
		<Heading tag="h3" class="text-lg font-light italic">
			{textureType}
		</Heading>
	</div>
</div>

// ui-react/src/views/render-new/Controls/NestedTextureHeader.tsx
import { Separator } from '../../../components/Separator';
import { getTextureData } from '../../../utils/render/texture';
import type { RenderConfig } from '../../../utils/render/config';

interface NestedTextureHeaderProps {
  textureName: string;
  renderConfig: RenderConfig;
}

export function NestedTextureHeader(props: NestedTextureHeaderProps) {
  const { textureName, renderConfig } = props;

  const { data } = getTextureData(renderConfig, textureName);

  return (
    <div className="flex justify-between">
      <h2 className="text-lg font-bold italic">Contained Texture</h2>
      <div className="flex gap-2">
        <h3 className="text-lg font-light not-italic">{textureName}</h3>
        <Separator vertical />
        <h3 className="text-lg font-light italic">{data.type}</h3>
      </div>
    </div>
  );
}
