// ui/src/lib/Separator.svelte
<script lang="ts">
	type Props = {
		vertical?: boolean;
		class?: string;
	};

	const { vertical, class: className }: Props = $props();
</script>

{#if vertical}
	<div class={['border-r-[1px] border-zinc-600', className]}></div>
{:else}
	<div class={['border-b-[1px] border-zinc-600', className]}></div>
{/if}

// ui-react/src/components/Separator.tsx
interface SeparatorProps {
  vertical?: boolean;
  className?: string;
}

export default function Separator({ vertical, className }: SeparatorProps) {
  if (vertical) {
    return <div className={`my-0.5 border-r border-zinc-600 ${className ?? ''}`} />;
  }
  return <div className={`my-0.5 border-b border-zinc-600 ${className ?? ''}`} />;
}
