// ui/src/routes/(authenticated)/renders/+page.svelte
<script lang="ts">
	import { Spinner, Alert } from 'flowbite-svelte';
	import { auth } from '$lib/state/auth.svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import { getAllRenders } from '$lib/utils/api';
	import RenderPreviewCard from './RenderPreviewCard.svelte';
	import NewRenderCard from './NewRenderCard.svelte';

	const token = auth.validToken;
	const user = auth.validUser;

	const allRendersQuery = createQuery({
		queryKey: ['renders', token],
		queryFn: async () => {
			return await getAllRenders(token);
		}
	});

	const canCreateNewRender = $derived(
		user.max_renders === null ||
			($allRendersQuery.data !== undefined &&
				$allRendersQuery.data.length < user.max_renders)
	);
</script>

<div class="flex w-full flex-col p-12">
	{#if $allRendersQuery.isPending}
		<div class="flex w-full justify-center py-8">
			<Spinner size="12" color="primary" />
			<span class="ml-2">Loading renders...</span>
		</div>
	{:else if $allRendersQuery.isError}
		<Alert color="red" class="w-full">
			<span class="font-medium">Error loading renders</span>
		</Alert>
	{:else if $allRendersQuery.isSuccess}
		<div class="flex w-full flex-wrap justify-center gap-4">
			{#each $allRendersQuery.data as render}
				<div class="w-80">
					<RenderPreviewCard {render} />
				</div>
			{/each}
			{#if canCreateNewRender}
				<div class="w-80">
					<NewRenderCard />
				</div>
			{/if}
		</div>
	{/if}
</div>

<!-- using Tailwind classes directly in HTML instead of CSS -->

// ui-react/src/views/renders/index.tsx
import { Spinner, Alert } from 'flowbite-react';
import { useAuth } from '../../utils/auth';
import { useRenders } from '../../hooks/useRenders';
import RenderPreviewCard from './RenderPreviewCard';
import NewRenderCard from './NewRenderCard';

export default function RendersPage() {
  const { user } = useAuth();
  const allRendersQuery = useRenders();

  const canCreateNewRender =
    (user?.max_renders ?? null) === null ||
    (allRendersQuery.data !== undefined &&
      allRendersQuery.data.length < (user?.max_renders ?? Infinity));

  return (
    <div className="flex w-full flex-col p-12 overflow-y-auto">
      {allRendersQuery.isPending && (
        <div className="flex w-full justify-center py-8">
          <Spinner size="xl" color="info" />
          <span className="ml-2">Loading renders...</span>
        </div>
      )}

      {allRendersQuery.isError && (
        <Alert color="failure" className="w-full">
          <span className="font-medium">Error loading renders</span>
        </Alert>
      )}

      {allRendersQuery.isSuccess && (
        <div className="flex w-full flex-wrap justify-center gap-4">
          {allRendersQuery.data.map((render) => (
            <div key={render.id} className="w-80">
              <RenderPreviewCard render={render} />
            </div>
          ))}
          {canCreateNewRender && (
            <div className="w-80">
              <NewRenderCard />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
