// ui/src/lib/TextArrayInputControl.svelte
<script lang="ts">
	import { Heading, Helper } from 'flowbite-svelte';
	import type { Snippet } from 'svelte';
	import {
		type SuperForm,
		arrayProxy,
		type FormPathArrays
	} from 'sveltekit-superforms';
	import z from 'zod';
	import { RenderConfigSchema } from './utils/render/config';
	import TextInput from './TextInput.svelte';
	import { getGridColumnsTemplateForPercentage } from './utils';

	const schema = RenderConfigSchema;

	type Props = {
		superform: SuperForm<z.infer<typeof schema>>;
		field: FormPathArrays<z.infer<typeof schema>>;
		type?: 'text' | 'number';
		label: string | Snippet;
		labelSpacePercentage?: 0 | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100;
		allowWrappingLabel?: boolean;
		labelPrefix?: Snippet;
		labelSuffix?: Snippet;
		valueLabels: string[];
	};

	const {
		superform,
		field,
		type = 'text',
		label,
		labelSpacePercentage = 40,
		allowWrappingLabel,
		labelPrefix,
		labelSuffix,
		valueLabels
	}: Props = $props();

	const {
		values: arrayValues,
		errors: arrayErrors,
		path,
		valueErrors
	} = $derived(arrayProxy(superform, field));

	const gridStr = getGridColumnsTemplateForPercentage(labelSpacePercentage);
</script>

<div class={['grid items-center', gridStr]}>
	<Heading tag="h6" class="mt-3 overflow-hidden font-normal">
		<span
			class={[
				'flex items-center gap-2',
				allowWrappingLabel ? 'whitespace-normal' : 'whitespace-nowrap'
			]}
		>
			{#if labelPrefix}
				{@render labelPrefix()}
			{/if}
			{#if typeof label === 'string'}
				{label}
			{:else}
				{@render label()}
			{/if}
			{#if labelSuffix}
				{@render labelSuffix()}
			{/if}
		</span>
	</Heading>
	<div class="flex flex-col">
		<div class="items-flex-end flex gap-2">
			{#each $arrayValues as _, i}
				<div class="flex w-full flex-col">
					<TextInput
						{superform}
						field={`${path}[${i}]`}
						{type}
						valueLabel={valueLabels[i]}
						extraIsErrored={$arrayErrors && $arrayErrors.length > 0}
					/>
					{#if $valueErrors[i] && $valueErrors[i].length > 0}
						<Helper color="red">{$valueErrors[i].join(', ')}</Helper>
					{:else}
						<span class="h-4"></span>
					{/if}
				</div>
			{/each}
		</div>
		{#if $arrayErrors}
			<Helper color="red">{$arrayErrors?.join(', ')}</Helper>
		{:else}
			<span class="h-4"></span>
		{/if}
	</div>
</div>

// ui-react/src/views/render-new/Controls/cards/form-controls/TextArrayInputControl.tsx
import { FormTextInput } from './FormTextInput';
import { getGridColumnsTemplateForPercentage } from './utils';
import type { DeepKeys } from '@tanstack/react-form';
import type { NormalizedRenderConfig } from '../../../../../utils/render/config';

interface TextArrayInputControlProps {
  form: any;
  field: DeepKeys<NormalizedRenderConfig>;
  type?: 'text' | 'number';
  label: string;
  labelSpacePercentage?: 0 | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100;
  allowWrappingLabel?: boolean;
  labelPrefix?: React.ReactNode;
  labelSuffix?: React.ReactNode;
  valueLabels: string[];
  unenforcedStep?: number;
}

export function TextArrayInputControl(props: TextArrayInputControlProps) {
  const {
    form,
    field,
    type = 'text',
    label,
    labelSpacePercentage = 40,
    allowWrappingLabel,
    labelPrefix,
    labelSuffix,
    valueLabels,
    unenforcedStep,
  } = props;

  const gridStr = getGridColumnsTemplateForPercentage(labelSpacePercentage);

  return (
    <div className={`grid items-center ${gridStr}`}>
      <h6 className="mt-3 overflow-hidden font-normal">
        <span
          className={`flex items-center gap-2 ${allowWrappingLabel ? 'whitespace-normal' : 'whitespace-nowrap'}`}
        >
          {labelPrefix}
          {label}
          {labelSuffix}
        </span>
      </h6>
      <div className="flex flex-col">
        <div className="items-flex-end flex gap-2">
          {valueLabels.map((valueLabel, i) => (
            <div key={i} className="flex w-full flex-col">
              <FormTextInput
                form={form}
                field={`${field}[${i}]` as DeepKeys<NormalizedRenderConfig>}
                type={type}
                valueLabel={valueLabel}
                unenforcedStep={unenforcedStep}
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
