// ui-react/src/views/render-new/ui/RangeControl.tsx
import { Label, RangeSlider } from 'flowbite-react';


interface RangeControlProps {
  form: any;
  field: string;
  label: string;
  labelPrefix?: React.ReactNode;
  labelSuffix?: React.ReactNode;
  min?: number;
  max?: number;
  step?: number;
}

export default function RangeControl({
  form,
  field,
  label,
  labelPrefix,
  labelSuffix,
  min,
  max,
  step,
}: RangeControlProps) {
  return (
    <form.Field name={field}>
      {(f: any) => (
        <Label className="mb-2 flex flex-col gap-1.5">
          <span className="flex justify-between">
            <span className="flex gap-2">
              {labelPrefix}
              {label}
              {labelSuffix}
            </span>
            <span>{f.state.value}</span>
          </span>
          <RangeSlider
            value={f.state.value as number}
            onChange={(e) => f.handleChange(Number(e.target.value))}
            min={min}
            max={max}
            step={step}
          />
        </Label>
      )}
    </form.Field>
  );
}

// ui/src/lib/RangeControl.svelte
<script lang="ts">
	import { Label, Range } from 'flowbite-svelte';
	import type { Snippet } from 'svelte';

	type Props = {
		label: string;
		labelPrefix?: Snippet;
		labelSuffix?: Snippet;
		value: number;
		min?: number;
		max?: number;
		step?: number;
	};

	let {
		label,
		labelPrefix,
		labelSuffix,
		value = $bindable(),
		min,
		max,
		step
	}: Props = $props();
</script>

<Label class="mb-2 flex flex-col gap-1.5">
	<span class="flex justify-between">
		<span class="flex gap-2">
			{#if labelPrefix}
				{@render labelPrefix()}
			{/if}
			{label}
			{#if labelSuffix}
				{@render labelSuffix()}
			{/if}
		</span>
		<span>{value}</span>
	</span>
	<Range bind:value {min} {max} {step} />
</Label>
