// ui-react/src/views/render-new/Controls/cards/form-controls/ToggleControl.tsx
import { ToggleSwitch } from 'flowbite-react';

interface ToggleControlProps {
  form: any;
  field: string;
  label: string;
  allowWrappingLabel?: boolean;
  labelPrefix?: React.ReactNode;
  labelSuffix?: React.ReactNode;
  disabled?: boolean;
}

export function ToggleControl(props: ToggleControlProps) {
  const { form, field, label, labelPrefix, labelSuffix, disabled } = props;

  return (
    <div className="flex max-w-full flex-col">
      <form.Field name={field}>
        {(f: any) => (
          <div className="flex w-full items-center justify-between py-2">
            <h6 className="overflow-hidden font-normal">
              <span className="flex items-center gap-2">
                {labelPrefix}
                {label}
                {labelSuffix}
              </span>
            </h6>
            <ToggleSwitch
              checked={f.state.value}
              onChange={(checked) => f.handleChange(checked)}
              disabled={disabled}
            />
          </div>
        )}
      </form.Field>
    </div>
  );
}

// ui/src/lib/ToggleControl.svelte
<script lang="ts">
	import { Heading, Toggle } from 'flowbite-svelte';
	import type { Snippet } from 'svelte';
	import type { ChangeEventHandler } from 'svelte/elements';

	type Props = {
		label: string | Snippet;
		allowWrappingLabel?: boolean;
		labelPrefix?: Snippet;
		labelSuffix?: Snippet;
		checked: boolean;
		onchange?: ChangeEventHandler<HTMLInputElement>;
		disabled?: boolean;
	};

	let {
		label,
		allowWrappingLabel,
		labelPrefix,
		labelSuffix,
		checked = $bindable(),
		onchange,
		disabled
	}: Props = $props();
</script>

<div class="flex max-w-full flex-col">
	<Toggle
		bind:checked
		{onchange}
		{disabled}
		size="large"
		class="flex w-full items-center justify-between py-2"
	>
		{#snippet offLabel()}
			<Heading tag="h6" class="overflow-hidden font-normal">
				<span
					class={[
						'flex items-center gap-2',
						allowWrappingLabel ? 'whitespace-normal' : 'whitespace-nowrap'
					]}
				>
					{#if labelPrefix}
						{@render labelPrefix()}
					{/if}
					{#if typeof label === 'string'}
						{label}
					{:else}
						{@render label()}
					{/if}
					{#if labelSuffix}
						{@render labelSuffix()}
					{/if}
				</span>
			</Heading>
		{/snippet}
	</Toggle>
</div>
