// ui-svelte/src/lib/ToggleControlUnbound.svelte
<script lang="ts">
	import { Heading, Toggle } from 'flowbite-svelte';
	import type { Snippet } from 'svelte';
	import type { FormEventHandler, ChangeEventHandler } from 'svelte/elements';

	type Props = {
		checked: boolean;
		oninput?: FormEventHandler<HTMLInputElement>;
		onchange?: ChangeEventHandler<HTMLInputElement>;
		label: string | Snippet;
		allowWrappingLabel?: boolean;
		labelPrefix?: Snippet;
		labelSuffix?: Snippet;
		disabled?: boolean;
	};

	let {
		checked,
		oninput,
		onchange,
		label,
		allowWrappingLabel,
		labelPrefix,
		labelSuffix,
		disabled
	}: Props = $props();
</script>

<div class="flex max-w-full flex-col">
	<Toggle
		bind:checked
		{oninput}
		{onchange}
		{disabled}
		size="large"
		class="flex w-full items-center justify-between py-2"
	>
		{#snippet offLabel()}
			<Heading tag="h6" class="overflow-hidden font-normal">
				<span
					class={[
						'flex items-center gap-2',
						allowWrappingLabel ? 'whitespace-normal' : 'whitespace-nowrap'
					]}
				>
					{#if labelPrefix}
						{@render labelPrefix()}
					{/if}
					{#if typeof label === 'string'}
						{label}
					{:else}
						{@render label()}
					{/if}
					{#if labelSuffix}
						{@render labelSuffix()}
					{/if}
				</span>
			</Heading>
		{/snippet}
	</Toggle>
</div>

// ui-react/src/components/ui/ToggleControlUnbound.tsx
import { ToggleSwitch } from 'flowbite-react';
import type { ChangeEvent, FormEvent } from 'react';

interface ToggleControlUnboundProps {
  checked: boolean;
  oninput?: (e: FormEvent<HTMLInputElement>) => void;
  onchange?: (e: ChangeEvent<HTMLInputElement>) => void;
  label: string;
  allowWrappingLabel?: boolean;
  labelPrefix?: React.ReactNode;
  labelSuffix?: React.ReactNode;
  disabled?: boolean;
}

export default function ToggleControlUnbound({
  checked,
  oninput,
  onchange,
  label,
  allowWrappingLabel,
  labelPrefix,
  labelSuffix,
  disabled,
}: ToggleControlUnboundProps) {
  return (
    <div className="flex max-w-full flex-col">
      <ToggleSwitch
        checked={checked}
        onChange={(e) => {
          onchange?.(e);
          oninput?.(e as unknown as FormEvent<HTMLInputElement>);
        }}
        disabled={disabled}
        label={
          <h6 className="overflow-hidden font-normal">
            <span
              className={`flex items-center gap-2 ${allowWrappingLabel ? 'whitespace-normal' : 'whitespace-nowrap'}`}
            >
              {labelPrefix}
              {label}
              {labelSuffix}
            </span>
          </h6>
        }
      />
    </div>
  );
}
