// ui/src/routes/(authenticated)/renders/new/MaterialControlsCard.svelte
<script lang="ts">
	import RangeControl from '$lib/RangeControl.svelte';
	import Separator from '$lib/Separator.svelte';
	import { RenderConfigSchema } from '$lib/utils/render/config';
	import { Button, Card, Heading } from 'flowbite-svelte';
	import {
		ChevronDownOutline,
		ChevronUpOutline,
		TrashBinOutline
	} from 'flowbite-svelte-icons';
	import { slide } from 'svelte/transition';
	import { getContext } from 'svelte';
	import type { FormPathLeaves, SuperForm } from 'sveltekit-superforms';
	import { z } from 'zod';
	import { getMaterialData } from '$lib/utils/render/material';
	import SelectControl from '$lib/SelectControl.svelte';
	import { fixReferences, type RenderConfigContext } from './utils';

	const schema = RenderConfigSchema;

	type Props = {
		superform: SuperForm<z.infer<typeof schema>>;
		materialName: string;
	};

	const { superform, materialName }: Props = $props();
	const { form } = $derived(superform);

	const renderConfigContext = getContext<RenderConfigContext>('renderConfig');

	const { data: materialData } = $derived(
		getMaterialData(renderConfigContext.get(), materialName)
	);

	function handleDeleteMaterial(name: string) {
		let newForm = { ...$form };
		delete newForm.materials[name];

		newForm = fixReferences(newForm);
		$form = newForm;
	}

	let isExpanded = $state(false);
	function handleToggleExpandCard() {
		isExpanded = !isExpanded;
	}
</script>

{#snippet controlsMaterial(name: string)}
	{@const { data } = getMaterialData(renderConfigContext.get(), name)}

	{#if data.type === 'dielectric'}
		{@render controlsMaterialDielectric(name)}
	{:else if data.type === 'lambertian'}
		{@render controlsMaterialLambertian(name)}
	{:else if data.type === 'specular'}
		{@render controlsMaterialSpecular(name)}
	{/if}
	{@render deleteMaterialButton(name)}
{/snippet}

{#snippet deleteMaterialButton(name: string)}
	<div class="flex w-full justify-end">
		<Button
			color="red"
			pill={true}
			onclick={() => handleDeleteMaterial(name)}
			class="p-2"
		>
			<TrashBinOutline class="h-6 w-6" />
		</Button>
	</div>
{/snippet}

{#snippet controlsTextureSelects(name: string)}
	{@const items = Object.keys(renderConfigContext.get().textures ?? {}).map(
		(key) => ({
			name: key,
			value: key
		})
	)}
	<SelectControl
		{superform}
		field={`materials.${name}.reflectance_texture` as FormPathLeaves<
			z.infer<typeof schema>,
			string
		>}
		label="Reflectance Texture"
		items={[...items]}
	/>
	<SelectControl
		{superform}
		field={`materials.${name}.emittance_texture` as FormPathLeaves<
			z.infer<typeof schema>,
			string
		>}
		label="Emittance Texture"
		items={[...items]}
	/>
{/snippet}

{#snippet controlsMaterialDielectric(name: string)}
	<RangeControl
		{superform}
		field={`materials.${name}.index_of_refraction` as FormPathLeaves<
			z.infer<typeof schema>,
			number
		>}
		label="Index of Refraction"
		min={1.0}
		max={10.0}
		step={0.01}
	/>
	{@render controlsTextureSelects(name)}
{/snippet}

{#snippet controlsMaterialLambertian(name: string)}
	{@render controlsTextureSelects(name)}
{/snippet}

{#snippet controlsMaterialSpecular(name: string)}
	<RangeControl
		{superform}
		field={`materials.${name}.roughness` as FormPathLeaves<
			z.infer<typeof schema>,
			number
		>}
		label="Roughness"
		min={0.0}
		max={1.0}
		step={0.01}
	/>
	{@render controlsTextureSelects(name)}
{/snippet}

<Card class="flex max-w-full flex-col !bg-zinc-800 !text-zinc-200">
	<button
		class="flex items-center justify-between p-4 pr-2"
		onclick={() => handleToggleExpandCard()}
	>
		<Heading tag="h2" class="text-xl font-bold">
			{materialName}
		</Heading>
		<div class="flex flex-row">
			<Heading tag="h3" class="text-lg font-light italic">
				{materialData.type}
			</Heading>
			{#if isExpanded}
				<ChevronUpOutline class="h-8 w-auto" />
			{:else}
				<ChevronDownOutline class="h-8 w-auto" />
			{/if}
		</div>
	</button>
	{#if isExpanded}
		<div transition:slide={{ duration: 300 }}>
			<Separator />
			<div class="flex flex-col gap-2 p-4">
				<!-- controls -->
				{@render controlsMaterial(materialName)}
			</div>
		</div>
	{/if}
</Card>

// ui-react/src/views/new-render/MaterialControlsCard.tsx
import { useState } from 'react';
import { Card, Button } from 'flowbite-react';
import { ChevronDownIcon, ChevronUpIcon } from 'flowbite-react';
import Separator from '../../components/Separator';
import RangeControl from '../../components/ui/RangeControl';
import SelectControl from '../../components/ui/SelectControl';
import { getMaterialData } from '../../utils/render/material';
import { fixReferences } from '../../utils/render/utils';
import type { RenderConfig } from '../../utils/render/config';

function TrashIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
    </svg>
  );
}

interface MaterialControlsCardProps {
  form: any;
  materialName: string;
}

export default function MaterialControlsCard({
  form,
  materialName,
}: MaterialControlsCardProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const renderConfig = form.state.values as RenderConfig;

  const { data: materialData } = getMaterialData(renderConfig, materialName);

  function handleDeleteMaterial(name: string) {
    const newMaterials = { ...renderConfig.materials };
    delete newMaterials[name];

    const newConfig: RenderConfig = {
      ...renderConfig,
      materials: newMaterials,
    };

    const fixed = fixReferences(newConfig);
    form.setFieldValue('geometrics', fixed.geometrics);
    form.setFieldValue('materials', fixed.materials);
    form.setFieldValue('scenes', fixed.scenes);
    form.setFieldValue('textures', fixed.textures);
  }

  // Texture select items
  const textureItems = Object.keys(renderConfig.textures ?? {}).map((key) => ({
    name: key,
    value: key,
  }));

  function TextureSelects({ name }: { name: string }) {
    return (
      <>
        <SelectControl
          form={form}
          field={`materials.${name}.reflectance_texture`}
          label="Reflectance Texture"
          items={textureItems}
        />
        <SelectControl
          form={form}
          field={`materials.${name}.emittance_texture`}
          label="Emittance Texture"
          items={textureItems}
        />
      </>
    );
  }

  function renderControls(name: string) {
    const { data } = getMaterialData(renderConfig, name);

    switch (data.type) {
      case 'dielectric':
        return (
          <>
            <RangeControl
              form={form}
              field={`materials.${name}.index_of_refraction`}
              label="Index of Refraction"
              min={1.0}
              max={10.0}
              step={0.01}
            />
            <TextureSelects name={name} />
          </>
        );
      case 'lambertian':
        return <TextureSelects name={name} />;
      case 'specular':
        return (
          <>
            <RangeControl
              form={form}
              field={`materials.${name}.roughness`}
              label="Roughness"
              min={0.0}
              max={1.0}
              step={0.01}
            />
            <TextureSelects name={name} />
          </>
        );
      default:
        return null;
    }
  }

  return (
    <Card className="flex max-w-full flex-col !bg-zinc-800 !text-zinc-200">
      <button
        type="button"
        className="flex items-center justify-between p-4 pr-2"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <h2 className="text-xl font-bold">{materialName}</h2>
        <div className="flex flex-row items-center gap-2">
          <h3 className="text-lg font-light italic">{materialData.type}</h3>
          {isExpanded ? (
            <ChevronUpIcon className="h-8 w-auto" />
          ) : (
            <ChevronDownIcon className="h-8 w-auto" />
          )}
        </div>
      </button>
      {isExpanded && (
        <div>
          <Separator />
          <div className="flex flex-col gap-2 p-4">
            {renderControls(materialName)}
            <div className="flex w-full justify-end">
              <Button
                color="failure"
                onClick={() => handleDeleteMaterial(materialName)}
                size="sm"
              >
                <TrashIcon className="h-5 w-5" />
              </Button>
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}
