// ui/src/routes/renders/new/ParametersControlsCard.svelte
<script lang="ts">
	import ControlsCard from '$lib/ControlsCard.svelte';
	import OptionalControl from '$lib/OptionalControl.svelte';
	import WarningIconAdvancedProperty from '$lib/property-icons/WarningIconAdvancedProperty.svelte';
	import { type RenderConfig, type RenderParameters } from '$lib/utils/render';
	import VectorInputControl from '$lib/VectorInputControl.svelte';
	import { getContext } from 'svelte';

	type Props = {
		parameters: RenderParameters;
	};

	const { parameters }: Props = $props();

	const renderConfig = getContext<RenderConfig>('renderConfig');

	/*
    	image_dimensions: [number, number];
	    tile_dimensions: [number, number];
	    gamma_correction: number;
	    samples_per_checkpoint: number;
	    total_checkpoints: number;
	    saved_checkpoint_limit?: number;
	    max_bounces: number;
	    use_scaling_truncation: boolean;
    */

	$inspect(renderConfig.parameters.saved_checkpoint_limit);
</script>

{#snippet controlsParameters(data: RenderParameters)}
	<VectorInputControl
		label="Size"
		bind:value={data.image_dimensions}
		valueLabel={['width', 'height']}
	/>
	<VectorInputControl
		label="Tile Size"
		bind:value={data.tile_dimensions}
		valueLabel={['width', 'height']}
	>
		{#snippet labelPrefix()}
			<WarningIconAdvancedProperty />
		{/snippet}
	</VectorInputControl>
	<VectorInputControl
		label="Gamma Correction"
		allowWrappingLabel
		labelSpacePercentage={70}
		bind:value={data.gamma_correction}
		valueLabel="gamma"
	>
		{#snippet labelPrefix()}
			<WarningIconAdvancedProperty />
		{/snippet}
	</VectorInputControl>
	<VectorInputControl
		label="Samples Per Checkpoint"
		labelSpacePercentage={70}
		bind:value={data.samples_per_checkpoint}
		valueLabel="samples"
	/>
	<VectorInputControl
		label="Total Checkpoints"
		labelSpacePercentage={70}
		bind:value={data.total_checkpoints}
		valueLabel="checkpoints"
	/>
	<OptionalControl
		label="Enforce Checkpoint Limit?"
		enabled={data.saved_checkpoint_limit !== undefined}
		onchange={(e) => {
			data.saved_checkpoint_limit = e.currentTarget.checked ? 1 : undefined;
		}}
	>
		<!-- <VectorInputControl
			label="Gamma Correction"
			allowWrappingLabel
			labelSpacePercentage={70}
			bind:value={data.gamma_correction}
			valueLabel="gamma"
		>
			{#snippet labelPrefix()}
				<WarningIconAdvancedProperty />
			{/snippet}
		</VectorInputControl> -->
		<!-- <VectorInputControl
			label="Total Checkpoints"
			labelSpacePercentage={70}
			bind:value={data.total_checkpoints}
			valueLabel="checkpoints"
		/> -->
		{#if data.saved_checkpoint_limit !== undefined}
			<VectorInputControl
				label="Saved Checkpoint Limit"
				labelSpacePercentage={70}
				bind:value={data.saved_checkpoint_limit}
				valueLabel="checkpoints"
			>
				{#snippet labelPrefix()}
					<WarningIconAdvancedProperty />
				{/snippet}
			</VectorInputControl>
		{/if}
	</OptionalControl>
	<VectorInputControl
		label="Max Light Bounces"
		labelSpacePercentage={70}
		bind:value={data.max_bounces}
		valueLabel="bounces"
	>
		{#snippet labelPrefix()}
			<WarningIconAdvancedProperty />
		{/snippet}
	</VectorInputControl>
	<!-- <VectorInputControl
		label="Use Scaling Truncation"
		labelSpacePercentage={70}
		bind:value={data.use_scaling_truncation}
		valueLabel="use"
	>
		{#snippet labelPrefix()}
			<WarningIconAdvancedProperty />
		{/snippet}
	</VectorInputControl> -->

	<!-- <RangeControl
		label="Vertical FOV (degrees)"
		bind:value={data.vertical_field_of_view_degrees}
		min={10.0}
		max={170.0}
		step={1.0}
	/>
	<Vector3InputControl
		label="Eye"
		bind:value={data.eye_location}
		valueLabels={['X', 'Y', 'Z']}
	/>
	<Vector3InputControl
		label="Target"
		bind:value={data.target_location}
		valueLabels={['X', 'Y', 'Z']}
	/>
	<Vector3InputControl
		label="View Up"
		bind:value={data.view_up}
		valueLabels={['X', 'Y', 'Z']}
	/>
	<RangeControl
		label="Defocus Angle (degrees)"
		bind:value={data.defocus_angle_degrees}
		min={0.0}
		step={1.0}
	>
		{#snippet labelPrefix()}
			<InfoCircleOutline class="text-amber-400" />
			<Tooltip>
				<Heading tag="h6">Incorrect Preview</Heading>
				<P>Editing this property will not affect the preview.</P>
				<P
					>You may only be able to see this property's effects by creating a
					render.</P
				>
			</Tooltip>
		{/snippet}
	</RangeControl> -->
	<!-- <RangeControl label="Focus Distance" bind:value={data.focus_distance} /> -->
{/snippet}

<ControlsCard startExpanded leftLabel="parameters" leftLabelStyle="light">
	<div class="flex flex-col gap-2 p-4">
		<!-- controls -->
		{@render controlsParameters(parameters)}
	</div>
</ControlsCard>

// ui-react/src/views/new-render/ParametersControlsCard.tsx
import ControlsCard from '../../components/ControlsCard';
import OptionalControlUnbound from '../../components/ui/OptionalControlUnbound';
import WarningIconAdvancedProperty from '../../components/icons/WarningIconAdvancedProperty';
import TextInputControl from '../../components/ui/TextInputControl';
import TextArrayInputControl from '../../components/ui/TextArrayInputControl';
import ToggleControl from '../../components/ui/ToggleControl';
import { Tooltip } from 'flowbite-react';
import { useAuth } from '../../utils/auth';
import { useState } from 'react';
import type { RenderConfig } from '../../utils/render/config';

interface ParametersControlsCardProps {
  form: any;
}

export default function ParametersControlsCard({
  form,
}: ParametersControlsCardProps) {
  const { validUser } = useAuth();
  const renderConfig = form.state.values as RenderConfig;
  const parameters = renderConfig.parameters;
  const savedCheckpointLimit = parameters.saved_checkpoint_limit ?? 1;
  const maxCheckpoints = validUser.max_checkpoints_per_render;

  const [savedCheckpointLimitLocal, setSavedCheckpointLimitLocal] =
    useState(savedCheckpointLimit);

  const isCheckpointLimitEnabled =
    form.state.values.parameters.saved_checkpoint_limit !== undefined;

  return (
    <ControlsCard leftLabel="parameters" leftLabelStyle="light" startExpanded>
      <div className="flex flex-col gap-2 p-4">
        <TextInputControl
          form={form}
          field="name"
          label="Name"
          valueLabel="name"
        />

        <TextArrayInputControl
          form={form}
          field="parameters.image_dimensions"
          label="Size"
          valueLabels={['width', 'height']}
          type="number"
        />

        <TextArrayInputControl
          form={form}
          field="parameters.tile_dimensions"
          label="Tile Size"
          valueLabels={['width', 'height']}
          type="number"
          labelSuffix={<WarningIconAdvancedProperty />}
        />

        <TextInputControl
          form={form}
          field="parameters.gamma_correction"
          label="Gamma Correction"
          labelSpacePercentage={70}
          allowWrappingLabel
          valueLabel="gamma"
          type="number"
          labelSuffix={<WarningIconAdvancedProperty />}
        />

        <TextInputControl
          form={form}
          field="parameters.samples_per_checkpoint"
          label="Samples Per Checkpoint"
          labelSpacePercentage={70}
          valueLabel="samples"
          type="number"
        />

        <TextInputControl
          form={form}
          field="parameters.total_checkpoints"
          label="Total Checkpoints"
          labelSpacePercentage={70}
          valueLabel="checkpoints"
          type="number"
        />

        <OptionalControlUnbound
          label="Enforce Checkpoint Limit?"
          checked={isCheckpointLimitEnabled}
          oninput={(e) => {
            form.setFieldValue(
              'parameters.saved_checkpoint_limit',
              (e as unknown as React.ChangeEvent<HTMLInputElement>).target.checked
                ? savedCheckpointLimitLocal
                : undefined
            );
          }}
          disabled={maxCheckpoints !== null}
          labelSuffix={<WarningIconAdvancedProperty />}
        >
          <TextInputControl
            form={form}
            oninput={(e) => {
              setSavedCheckpointLimitLocal(
                Number((e as React.FormEvent<HTMLInputElement>).currentTarget.value)
              );
            }}
            onchange={(e) => {
              setSavedCheckpointLimitLocal(
                Number((e as React.ChangeEvent<HTMLInputElement>).currentTarget.value)
              );
            }}
            field="parameters.saved_checkpoint_limit"
            label="Saved Checkpoint Limit"
            labelSpacePercentage={70}
            valueLabel="checkpoints"
            type="number"
            labelSuffix={<WarningIconAdvancedProperty />}
          />
        </OptionalControlUnbound>

        {maxCheckpoints !== null && (
          <Tooltip
            content={`As a non-admin user, you are limited to ${maxCheckpoints} checkpoints saved per render.`}
          >
            <span className="text-sm text-zinc-400">
              ⓘ Checkpoint limit enforced
            </span>
          </Tooltip>
        )}

        <TextInputControl
          form={form}
          field="parameters.max_bounces"
          label="Max Light Bounces"
          labelSpacePercentage={70}
          valueLabel="bounces"
          type="number"
          labelSuffix={<WarningIconAdvancedProperty />}
        />

        <ToggleControl
          form={form}
          field="parameters.use_scaling_truncation"
          label="Use Scaling Truncation"
          labelSuffix={<WarningIconAdvancedProperty />}
        />
      </div>
    </ControlsCard>
  );
}
