// ui-react/src/views/render-new/Controls/NestedGeometricHeader.tsx
import { Separator } from '../../../components/Separator';
import { getGeometricData } from '../../../utils/render/geometric';
import type { RenderConfig } from '../../../utils/render/config';

interface NestedGeometricHeaderProps {
  geometricName: string;
  renderConfig: RenderConfig;
}

export function NestedGeometricHeader(props: NestedGeometricHeaderProps) {
  const { geometricName, renderConfig } = props;

  const { data } = getGeometricData(renderConfig, geometricName);

  return (
    <div className="flex justify-between">
      <h2 className="text-lg font-bold italic">Contained Geometric</h2>
      <div className="flex gap-2">
        <h3 className="text-lg font-light not-italic">{geometricName}</h3>
        <Separator vertical />
        <h3 className="text-lg font-light italic">{data.type}</h3>
      </div>
    </div>
  );
}

// ui/src/routes/(authenticated)/renders/new/NestedGeometricHeader.svelte
<script lang="ts">
	import { Heading } from 'flowbite-svelte';
	import Separator from '$lib/Separator.svelte';
	import { type RenderConfig } from '$lib/utils/render/config';
	import { getContext } from 'svelte';
	import {
		type GeometricData,
		getGeometricData
	} from '$lib/utils/render/geometric';

	type Props = {
		geometricName: string;
	};

	const { geometricName }: Props = $props();

	const renderConfig = getContext<RenderConfig>('renderConfig');

	const { data } = getGeometricData(renderConfig, geometricName);
	const { type: geometricType } = data;
</script>

<div class="flex justify-between">
	<Heading tag="h2" class="text-lg font-bold italic"
		>Contained Geometric</Heading
	>
	<div class="flex gap-2">
		<Heading tag="h3" class="text-lg font-light not-italic">
			{geometricName}
		</Heading>
		<!-- {#if typeof data === 'string'}
			<Heading tag="h3" class="text-lg font-light not-italic">{data}</Heading>
		{:else}
			<Heading tag="h3" class="text-lg font-light italic">inline</Heading>
		{/if} -->
		<Separator vertical />
		<Heading tag="h3" class="text-lg font-light italic">{geometricType}</Heading
		>
	</div>
</div>
