// ui-react/src/views/render-new/Controls/NewGeometricSpeedDial.tsx
import { Dropdown, DropdownItem } from 'flowbite-react';
import { defaultGeometricForType, type GeometricData } from '../../../utils/render/geometric';
import { capitalize, getNextUniqueName } from '../../../utils/render/utils';
import type { RenderForm } from '../../../hooks/useRenderForm';
import { useStore } from '@tanstack/react-form';
import type { NormalizedSceneData } from '../../../utils/render/scene';
import { HiPlus } from 'react-icons/hi2';

type GeometricType = Exclude<GeometricData['type'], 'obj_model'>;

const GEOMETRIC_TYPES: { type: GeometricType; label: string }[] = [
  { type: 'box', label: 'Box' },
  { type: 'list', label: 'List' },
  { type: 'rotate_x', label: 'Rotate X' },
  { type: 'rotate_y', label: 'Rotate Y' },
  { type: 'rotate_z', label: 'Rotate Z' },
  { type: 'translate', label: 'Translate' },
  { type: 'parallelogram', label: 'Parallelogram' },
  { type: 'sphere', label: 'Sphere' },
  { type: 'triangle', label: 'Triangle' },
  { type: 'constant_volume', label: 'Constant Volume' },
];

interface NewGeometricSpeedDialProps {
  form: RenderForm;
}

export function NewGeometricSpeedDial(props: NewGeometricSpeedDialProps) {
  const { form } = props;

  const formValues = useStore(form.store, (state) => state.values);

  function handleNewGeometric(type: GeometricType) {
    const newGeometric = defaultGeometricForType(type);
    const nextName = getNextUniqueName(formValues.geometrics ?? {}, `New ${capitalize(type)}`);

    const newGeometrics = {
      ...(formValues.geometrics ?? {}),
      [nextName]: newGeometric,
    };
    const activeSceneData = formValues.scenes?.[formValues.active_scene] as NormalizedSceneData;
    const newScenes = {
      ...formValues.scenes,
      [formValues.active_scene]: {
        ...activeSceneData,
        geometrics: [...activeSceneData.geometrics, nextName],
      },
    };

    form.setFieldValue('geometrics', newGeometrics);
    form.setFieldValue('scenes', newScenes);
  }

  return (
    <Dropdown label={<HiPlus className="h-6 w-6" />} arrowIcon={false} color="light" size="sm">
      {GEOMETRIC_TYPES.map((item) => (
        <DropdownItem
          key={item.label}
          onClick={() => {
            handleNewGeometric(item.type);
          }}
        >
          <div className="flex items-center gap-2">
            <HiPlus className="h-4 w-4" />
            {item.label}
          </div>
        </DropdownItem>
      ))}
    </Dropdown>
  );
}

// ui/src/routes/(authenticated)/renders/new/NewGeometricSpeedDial.svelte
<script lang="ts">
	import { RenderConfigSchema } from '$lib/utils/render/config';
	import {
		defaultGeometricForType,
		type GeometricData
	} from '$lib/utils/render/geometric';
	import { capitalize, getNextUniqueName } from '$lib/utils/render/utils';
	import {
		Listgroup,
		ListgroupItem,
		SpeedDial,
		SpeedDialTrigger,
		Tooltip
	} from 'flowbite-svelte';
	import { PlusOutline } from 'flowbite-svelte-icons';
	import { type SuperForm } from 'sveltekit-superforms';
	import { z } from 'zod';

	const schema = RenderConfigSchema;
	type Props = {
		superform: SuperForm<z.infer<typeof schema>>;
	};

	const { superform }: Props = $props();
	const { form } = $derived(superform);

	function handleNewGeometric(
		type: Exclude<GeometricData['type'], 'obj_model'>
	) {
		const newGeometric = defaultGeometricForType(type);
		const nextName = getNextUniqueName(
			$form.geometrics,
			`New ${capitalize(type)}`
		);

		const newForm = {
			...$form,
			geometrics: { ...$form.geometrics, [nextName]: newGeometric },
			scenes: {
				...$form.scenes,
				[$form.active_scene]: {
					...$form.scenes[$form.active_scene],
					geometrics: [...$form.scenes[$form.active_scene].geometrics, nextName]
				}
			}
		};

		$form = newForm;
	}
</script>

<SpeedDialTrigger transition={undefined}>
	{#snippet icon()}
		<PlusOutline size="xl" />
	{/snippet}
</SpeedDialTrigger>
<SpeedDial placement="top-end">
	<Listgroup active>
		<ListgroupItem onclick={() => handleNewGeometric('box')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Box
		</ListgroupItem>
		<ListgroupItem onclick={() => handleNewGeometric('list')} class="flex">
			<PlusOutline size="md" class="me-2" />
			List
		</ListgroupItem>
		<ListgroupItem
			disabled
			class="flex"
			onclick={() => {
				console.warn('obj_model geometric not implemented yet');
				// TODO: implement obj_model geometric
				// handleNewGeometric('obj_model')
			}}
		>
			<PlusOutline size="md" class="me-2" />
			.obj Model
		</ListgroupItem>
		<Tooltip><span>.obj models are not yet implemented</span></Tooltip>
		<ListgroupItem onclick={() => handleNewGeometric('rotate_x')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Rotate X
		</ListgroupItem>
		<ListgroupItem onclick={() => handleNewGeometric('rotate_y')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Rotate Y
		</ListgroupItem>
		<ListgroupItem onclick={() => handleNewGeometric('rotate_z')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Rotate Z
		</ListgroupItem>
		<ListgroupItem onclick={() => handleNewGeometric('translate')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Translate
		</ListgroupItem>
		<ListgroupItem
			onclick={() => handleNewGeometric('parallelogram')}
			class="flex"
		>
			<PlusOutline size="md" class="me-2" />
			Parallelogram
		</ListgroupItem>
		<ListgroupItem onclick={() => handleNewGeometric('sphere')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Sphere
		</ListgroupItem>
		<ListgroupItem onclick={() => handleNewGeometric('triangle')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Triangle
		</ListgroupItem>
		<ListgroupItem
			onclick={() => handleNewGeometric('constant_volume')}
			class="flex"
		>
			<PlusOutline size="md" class="me-2" />
			Constant Volume
		</ListgroupItem>
	</Listgroup>
</SpeedDial>
