// ui-react/src/views/render-new/Controls/NewTextureSpeedDial.tsx
import { Dropdown, DropdownItem } from 'flowbite-react';
import { defaultTextureForType, type TextureData } from '../../../utils/render/texture';
import { capitalize, getNextUniqueName } from '../../../utils/render/utils';
import type { RenderForm } from '../../../hooks/useRenderForm';
import { useStore } from '@tanstack/react-form';
import { HiPlus } from 'react-icons/hi2';

type TextureType = Exclude<TextureData['type'], 'checker' | 'image'>;

interface NewTextureSpeedDialProps {
  form: RenderForm;
}

export function NewTextureSpeedDial(props: NewTextureSpeedDialProps) {
  const { form } = props;

  const formValues = useStore(form.store, (state) => state.values);

  function handleNewTexture(type: TextureType) {
    const newTexture = defaultTextureForType(type);
    const nextName = getNextUniqueName(formValues.textures ?? {}, `New ${capitalize(type)}`);

    form.setFieldValue('textures', {
      ...formValues.textures,
      [nextName]: newTexture,
    });
  }

  return (
    <Dropdown label={<HiPlus className="h-6 w-6" />} arrowIcon={false} color="light" size="sm">
      <DropdownItem disabled>
        <div className="flex items-center gap-2">
          <HiPlus className="h-4 w-4" />
          Checker Texture
        </div>
      </DropdownItem>
      <DropdownItem disabled>
        <div className="flex items-center gap-2">
          <HiPlus className="h-4 w-4" />
          Image Texture
        </div>
      </DropdownItem>
      <DropdownItem onClick={() => handleNewTexture('color')}>
        <div className="flex items-center gap-2">
          <HiPlus className="h-4 w-4" />
          Color Texture
        </div>
      </DropdownItem>
    </Dropdown>
  );
}

// ui/src/routes/(authenticated)/renders/new/NewTextureSpeedDial.svelte
<script lang="ts">
	import { RenderConfigSchema } from '$lib/utils/render/config';
	import {
		defaultTextureForType,
		type TextureData
	} from '$lib/utils/render/texture';
	import { capitalize, getNextUniqueName } from '$lib/utils/render/utils';
	import {
		Listgroup,
		ListgroupItem,
		SpeedDial,
		SpeedDialTrigger,
		Tooltip
	} from 'flowbite-svelte';
	import { PlusOutline } from 'flowbite-svelte-icons';
	import { type SuperForm } from 'sveltekit-superforms';
	import { z } from 'zod';

	const schema = RenderConfigSchema;
	type Props = {
		superform: SuperForm<z.infer<typeof schema>>;
	};

	const { superform }: Props = $props();
	const { form } = $derived(superform);

	function handleNewTexture(
		type: Exclude<TextureData['type'], 'checker' | 'image'>
	) {
		const newTexture = defaultTextureForType(type);
		const nextName = getNextUniqueName(
			$form.textures,
			`New ${capitalize(type)}`
		);

		$form.textures[nextName] = newTexture;
	}
</script>

<SpeedDialTrigger transition={undefined}>
	{#snippet icon()}
		<PlusOutline size="xl" />
	{/snippet}
</SpeedDialTrigger>
<SpeedDial placement="top-end">
	<Listgroup active>
		<ListgroupItem
			disabled
			class="flex"
			onclick={() => {
				console.warn('checker texture not implemented yet');
				// TODO: implement checker texture
				// handleNewTexture('checker')
			}}
		>
			<PlusOutline size="md" class="me-2" />
			Checker Texture
		</ListgroupItem>
		<Tooltip><span>Checker Textures are not yet implemented</span></Tooltip>
		<ListgroupItem
			disabled
			onclick={() => {
				console.warn('image texture not implemented yet');
				// TODO: implement image texture
				// handleNewTexture('image')
			}}
			class="flex"
		>
			<PlusOutline size="md" class="me-2" />
			Image Texture
		</ListgroupItem>
		<Tooltip><span>Image Textures are not yet implemented</span></Tooltip>
		<ListgroupItem onclick={() => handleNewTexture('color')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Color Texture
		</ListgroupItem>
	</Listgroup>
</SpeedDial>
