// ui-react/src/views/new-render/NewTextureSpeedDial.tsx
import { Dropdown } from 'flowbite-react';
import {
  defaultTextureForType,
  type TextureData,
} from '../../utils/render/texture';
import { capitalize, getNextUniqueName } from '../../utils/render/utils';
import type { RenderConfig } from '../../utils/render/config';

function PlusIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
    </svg>
  );
}

type TextureType = Exclude<TextureData['type'], 'checker' | 'image'>;

interface NewTextureSpeedDialProps {
  form: any;
}

export default function NewTextureSpeedDial({ form }: NewTextureSpeedDialProps) {
  const formValues = form.state.values as RenderConfig;

  function handleNewTexture(type: TextureType) {
    const newTexture = defaultTextureForType(type as any);
    const nextName = getNextUniqueName(
      formValues.textures,
      `New ${capitalize(type)}`
    );

    form.setFieldValue('textures', {
      ...formValues.textures,
      [nextName]: newTexture,
    });
  }

  return (
    <Dropdown
      label={<PlusIcon className="h-6 w-6" />}
      arrowIcon={false}
      color="light"
      size="sm"
    >
      <Dropdown.Item disabled>
        <div className="flex items-center gap-2">
          <PlusIcon className="h-4 w-4" />
          Checker Texture
        </div>
      </Dropdown.Item>
      <Dropdown.Item disabled>
        <div className="flex items-center gap-2">
          <PlusIcon className="h-4 w-4" />
          Image Texture
        </div>
      </Dropdown.Item>
      <Dropdown.Item onClick={() => handleNewTexture('color')}>
        <div className="flex items-center gap-2">
          <PlusIcon className="h-4 w-4" />
          Color Texture
        </div>
      </Dropdown.Item>
    </Dropdown>
  );
}

// ui/src/routes/(authenticated)/renders/new/NewTextureSpeedDial.svelte
<script lang="ts">
	import { RenderConfigSchema } from '$lib/utils/render/config';
	import {
		defaultTextureForType,
		type TextureData
	} from '$lib/utils/render/texture';
	import { capitalize, getNextUniqueName } from '$lib/utils/render/utils';
	import {
		Listgroup,
		ListgroupItem,
		SpeedDial,
		SpeedDialTrigger,
		Tooltip
	} from 'flowbite-svelte';
	import { PlusOutline } from 'flowbite-svelte-icons';
	import { type SuperForm } from 'sveltekit-superforms';
	import { z } from 'zod';

	const schema = RenderConfigSchema;
	type Props = {
		superform: SuperForm<z.infer<typeof schema>>;
	};

	const { superform }: Props = $props();
	const { form } = $derived(superform);

	function handleNewTexture(
		type: Exclude<TextureData['type'], 'checker' | 'image'>
	) {
		const newTexture = defaultTextureForType(type);
		const nextName = getNextUniqueName(
			$form.textures,
			`New ${capitalize(type)}`
		);

		$form.textures[nextName] = newTexture;
	}
</script>

<SpeedDialTrigger transition={undefined}>
	{#snippet icon()}
		<PlusOutline size="xl" />
	{/snippet}
</SpeedDialTrigger>
<SpeedDial placement="top-end">
	<Listgroup active>
		<ListgroupItem
			disabled
			class="flex"
			onclick={() => {
				console.warn('checker texture not implemented yet');
				// TODO: implement checker texture
				// handleNewTexture('checker')
			}}
		>
			<PlusOutline size="md" class="me-2" />
			Checker Texture
		</ListgroupItem>
		<Tooltip><span>Checker Textures are not yet implemented</span></Tooltip>
		<ListgroupItem
			disabled
			onclick={() => {
				console.warn('image texture not implemented yet');
				// TODO: implement image texture
				// handleNewTexture('image')
			}}
			class="flex"
		>
			<PlusOutline size="md" class="me-2" />
			Image Texture
		</ListgroupItem>
		<Tooltip><span>Image Textures are not yet implemented</span></Tooltip>
		<ListgroupItem onclick={() => handleNewTexture('color')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Color Texture
		</ListgroupItem>
	</Listgroup>
</SpeedDial>
