// ui-react/src/views/render-new/TextureControlsCard.tsx
import { useState } from 'react';
import { Card, Button } from 'flowbite-react';
import { ChevronDownIcon, ChevronUpIcon } from 'flowbite-react';
import { motion, AnimatePresence } from 'framer-motion';
import Separator from '../../components/Separator';
import TextInputControl from './ui/TextInputControl';
import TextArrayInputControl from './ui/TextArrayInputControl';
import InfoIconAdditionalInfo from './icons/InfoIconAdditionalInfo';
import NestedTextureHeader from './NestedTextureHeader';
import { getTextureData } from '../../utils/render/texture';
import { fixReferences } from '../../utils/render/utils';
import type { RenderConfig } from '../../utils/render/config';
import { useStore } from '@tanstack/react-form';

function TrashIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
    </svg>
  );
}

interface TextureControlsCardProps {
  form: any;
  textureName: string;
}

export default function TextureControlsCard({
  form,
  textureName,
}: TextureControlsCardProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const renderConfig = useStore(form.store, (state: any) => state.values) as RenderConfig;

  const { data: textureData } = getTextureData(renderConfig, textureName);

  function handleDeleteTexture(name: string) {
    const newTextures = { ...renderConfig.textures };
    delete newTextures[name];

    const newConfig: RenderConfig = {
      ...renderConfig,
      textures: newTextures,
    };

    const fixed = fixReferences(newConfig);
    form.setFieldValue('textures', fixed.textures);
    form.setFieldValue('materials', fixed.materials);
    form.setFieldValue('geometrics', fixed.geometrics);
    form.setFieldValue('scenes', fixed.scenes);
  }

  function SubTexture({ name }: { name: string }) {
    return (
      <>
        <NestedTextureHeader textureName={name} renderConfig={renderConfig} />
        {renderControls(name)}
      </>
    );
  }

  function renderControls(name: string) {
    const { data } = getTextureData(renderConfig, name);

    return (
      <>
        {data.type === 'checker' && (
          <>
            <TextInputControl
              form={form}
              field={`textures.${name}.scale`}
              label="Scale"
              valueLabel="scale"
              type="number"
            />
            <Separator />
            <SubTexture name={(data as any).even_texture} />
            <Separator />
            <SubTexture name={(data as any).odd_texture} />
          </>
        )}
        {data.type === 'image' && <p className="text-sm text-zinc-500">Image texture — TODO</p>}
        {data.type === 'color' && (
          <TextArrayInputControl
            form={form}
            field={`textures.${name}.color`}
            label="Color"
            valueLabels={['red', 'green', 'blue']}
            type="number"
            unenforcedStep={0.01}
            labelSuffix={
              <InfoIconAdditionalInfo
                info={[
                  'Color values are typically between 0 and 1. For example, pure white would be [1, 1, 1].',
                  'Values can be set outside of this range, and will be affected by the "Use Scaling Truncation" parameter.',
                  'In the case of emissive textures, these values linearly correspond to the intensity of the emitted light.',
                ]}
              />
            }
          />
        )}
      </>
    );
  }

  return (
    <Card className="flex max-w-full flex-col !bg-zinc-800 !text-zinc-200 [&>div]:!p-0">
      <button
        type="button"
        className="flex items-center justify-between p-4 pr-2"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <h2 className="text-xl font-bold">{textureName}</h2>
        <div className="flex flex-row items-center gap-2">
          <h3 className="text-lg font-light italic">{textureData.type}</h3>
          {isExpanded ? (
            <ChevronUpIcon className="h-8 w-auto" />
          ) : (
            <ChevronDownIcon className="h-8 w-auto" />
          )}
        </div>
      </button>
      <AnimatePresence initial={false}>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: 'easeInOut' }}
            className="overflow-hidden"
          >
            <Separator />
            <div className="flex flex-col gap-2 p-4">
              {renderControls(textureName)}
              <div className="flex w-full justify-end">
                <Button
                  color="red"
                  onClick={() => handleDeleteTexture(textureName)}
                  size="sm"
                >
                  <TrashIcon className="h-5 w-5" />
                </Button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </Card>
  );
}

// ui/src/routes/(authenticated)/renders/new/TextureControlsCard.svelte
<script lang="ts">
	import Separator from '$lib/Separator.svelte';
	import { RenderConfigSchema } from '$lib/utils/render/config';
	import { Button, Card, Heading } from 'flowbite-svelte';
	import {
		ChevronDownOutline,
		ChevronUpOutline,
		TrashBinOutline
	} from 'flowbite-svelte-icons';
	import { slide } from 'svelte/transition';
	import { getContext } from 'svelte';
	import type {
		FormPathArrays,
		FormPathLeaves,
		SuperForm
	} from 'sveltekit-superforms';
	import { z } from 'zod';
	import {
		getTextureData,
		type TextureChecker
	} from '$lib/utils/render/texture';
	import TextInputControl from '$lib/TextInputControl.svelte';
	import TextArrayInputControl from '$lib/TextArrayInputControl.svelte';
	import InfoIconAdditionalInfo from '$lib/property-icons/InfoIconAdditionalInfo.svelte';
	import NestedTextureHeader from './NestedTextureHeader.svelte';
	import { fixReferences, type RenderConfigContext } from './utils';

	const schema = RenderConfigSchema;

	type Props = {
		superform: SuperForm<z.infer<typeof schema>>;
		textureName: string;
	};

	const { superform, textureName }: Props = $props();
	const { form } = $derived(superform);

	const renderConfigContext = getContext<RenderConfigContext>('renderConfig');

	const { data: textureData } = $derived(
		getTextureData(renderConfigContext.get(), textureName)
	);

	function handleDeleteTexture(name: string) {
		let newForm = { ...$form };
		delete newForm.textures[name];

		newForm = fixReferences(newForm);
		$form = newForm;
	}

	let isExpanded = $state(false);
	function handleToggleExpandCard() {
		isExpanded = !isExpanded;
	}
</script>

{#snippet controlsSubTexture(name: string)}
	<NestedTextureHeader textureName={name} />
	{@render controlsTexture(name, true)}
{/snippet}

{#snippet controlsTexture(name: string, isSubTexture: boolean)}
	{@const { data } = getTextureData(renderConfigContext.get(), name)}

	{#if data.type === 'checker'}
		{@render controlsTextureChecker(name)}
	{:else if data.type === 'image'}
		{@render controlsTextureImage(name)}
	{:else if data.type === 'color'}
		{@render controlsTextureSolidColor(name)}
	{/if}
	{#if !isSubTexture}
		{@render deleteTextureButton(name)}
	{/if}
{/snippet}

{#snippet deleteTextureButton(name: string)}
	<div class="flex w-full justify-end">
		<Button
			color="red"
			pill={true}
			onclick={() => handleDeleteTexture(name)}
			class="p-2"
		>
			<TrashBinOutline class="h-6 w-6" />
		</Button>
	</div>
{/snippet}

{#snippet controlsTextureChecker(name: string)}
	{@const { data } = getTextureData(renderConfigContext.get(), name)}
	<TextInputControl
		{superform}
		field={`textures.${name}.scale` as FormPathLeaves<
			z.infer<typeof schema>,
			number
		>}
		label="Scale"
		valueLabel="scale"
		type="number"
	/>
	<Separator />
	{@render controlsSubTexture((data as TextureChecker).even_texture)}
	<Separator />
	{@render controlsSubTexture((data as TextureChecker).odd_texture)}
{/snippet}

{#snippet controlsTextureImage(name: string)}
	<!-- TODO -->
{/snippet}

{#snippet controlsTextureSolidColor(name: string)}
	<TextArrayInputControl
		{superform}
		field={`textures.${name}.color` as FormPathArrays<z.infer<typeof schema>>}
		label="Color"
		valueLabels={['red', 'green', 'blue']}
		type="number"
		unenforcedStep={0.01}
	>
		{#snippet labelSuffix()}
			<InfoIconAdditionalInfo
				info={[
					'Color values are typically between 0 and 1. For example, pure white would be [1, 1, 1].',
					'Values can be set outside of this range, and will be affected by the "Use Scaling Truncation" parameter.',
					'In the case of emissive textures, these values linearly correspond to the intensity of the emitted light.'
				]}
			/>
		{/snippet}
	</TextArrayInputControl>
{/snippet}

<Card class="flex max-w-full flex-col !bg-zinc-800 !text-zinc-200">
	<button
		class="flex items-center justify-between p-4 pr-2"
		onclick={() => handleToggleExpandCard()}
	>
		{#if typeof textureName === 'string'}
			<Heading tag="h2" class="text-xl font-bold">
				{textureName}
			</Heading>
		{:else}
			<Heading tag="h2" class="text-xl font-light italic">inline</Heading>
		{/if}
		<div class="flex flex-row">
			<Heading tag="h3" class="text-lg font-light italic">
				{textureData.type}
			</Heading>
			{#if isExpanded}
				<ChevronUpOutline class="h-8 w-auto" />
			{:else}
				<ChevronDownOutline class="h-8 w-auto" />
			{/if}
		</div>
	</button>
	{#if isExpanded}
		<div transition:slide={{ duration: 300 }}>
			<Separator />
			<div class="flex flex-col gap-2 p-4">
				<!-- controls -->
				{@render controlsTexture(textureName, false)}
			</div>
		</div>
	{/if}
</Card>
