// ui/src/components/form-controls/ToggleControlUnbound.tsx
import { ToggleSwitch } from 'flowbite-react';
import type { ChangeEvent, InputEvent } from 'react';

export type ToggleControlUnboundProps = {
  checked: boolean;
  onInput?: (e: InputEvent<HTMLInputElement>) => void;
  onChange?: (e: ChangeEvent<HTMLInputElement>) => void;
  label: string;
  allowWrappingLabel?: boolean;
  labelPrefix?: React.ReactNode;
  labelSuffix?: React.ReactNode;
  disabled?: boolean;
};

export function ToggleControlUnbound(props: ToggleControlUnboundProps) {
  const { checked, onInput, onChange, label, labelPrefix, labelSuffix, disabled } = props;

  return (
    <div className="flex max-w-full flex-col">
      <div className="flex items-center gap-2">
        {labelPrefix}
        <ToggleSwitch
          checked={checked}
          onChange={(checked) => {
            const syntheticEvent = {
              target: { checked },
            } as ChangeEvent<HTMLInputElement>;
            onChange?.(syntheticEvent);
            onInput?.(syntheticEvent as unknown as InputEvent<HTMLInputElement>);
          }}
          disabled={disabled}
          label={label}
        />
        {labelSuffix}
      </div>
    </div>
  );
}

// ui-svelte/src/lib/ToggleControlUnbound.svelte
<script lang="ts">
	import { Heading, Toggle } from 'flowbite-svelte';
	import type { Snippet } from 'svelte';
	import type { FormEventHandler, ChangeEventHandler } from 'svelte/elements';

	type Props = {
		checked: boolean;
		oninput?: FormEventHandler<HTMLInputElement>;
		onchange?: ChangeEventHandler<HTMLInputElement>;
		label: string | Snippet;
		allowWrappingLabel?: boolean;
		labelPrefix?: Snippet;
		labelSuffix?: Snippet;
		disabled?: boolean;
	};

	let {
		checked,
		oninput,
		onchange,
		label,
		allowWrappingLabel,
		labelPrefix,
		labelSuffix,
		disabled
	}: Props = $props();
</script>

<div class="flex max-w-full flex-col">
	<Toggle
		bind:checked
		{oninput}
		{onchange}
		{disabled}
		size="large"
		class="flex w-full items-center justify-between py-2"
	>
		{#snippet offLabel()}
			<Heading tag="h6" class="overflow-hidden font-normal">
				<span
					class={[
						'flex items-center gap-2',
						allowWrappingLabel ? 'whitespace-normal' : 'whitespace-nowrap'
					]}
				>
					{#if labelPrefix}
						{@render labelPrefix()}
					{/if}
					{#if typeof label === 'string'}
						{label}
					{:else}
						{@render label()}
					{/if}
					{#if labelSuffix}
						{@render labelSuffix()}
					{/if}
				</span>
			</Heading>
		{/snippet}
	</Toggle>
</div>
