// ui-react/src/views/renders.tsx
import { Spinner, Alert } from 'flowbite-react';
import { useAuth } from '../utils/auth';
import { useRenders } from '../hooks/useRenders';
import RenderPreviewCard from '../components/RenderPreviewCard';
import NewRenderCard from '../components/NewRenderCard';

export default function RendersPage() {
  const { validUser } = useAuth();
  const allRendersQuery = useRenders();

  const canCreateNewRender =
    validUser.max_renders === null ||
    (allRendersQuery.data !== undefined &&
      allRendersQuery.data.length < validUser.max_renders);

  return (
    <div className="flex w-full flex-col p-12">
      {allRendersQuery.isPending && (
        <div className="flex w-full justify-center py-8">
          <Spinner size="xl" color="info" />
          <span className="ml-2">Loading renders...</span>
        </div>
      )}

      {allRendersQuery.isError && (
        <Alert color="failure" className="w-full">
          <span className="font-medium">Error loading renders</span>
        </Alert>
      )}

      {allRendersQuery.isSuccess && (
        <div className="flex w-full flex-wrap justify-center gap-4">
          {allRendersQuery.data.map((render) => (
            <div key={render.id} className="w-80">
              <RenderPreviewCard render={render} />
            </div>
          ))}
          {canCreateNewRender && (
            <div className="w-80">
              <NewRenderCard />
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ui/src/routes/renders/+page.svelte
<script lang="ts">
	import { Spinner, Alert } from 'flowbite-svelte';
	import { getToken } from '$lib/state/auth.svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import { getAllRenders } from '$lib/utils/api';
	import RenderPreviewCard from './RenderPreviewCard.svelte';
	import NewRenderCard from './NewRenderCard.svelte';

	const authToken = getToken();

	const allRendersQuery = createQuery({
		queryKey: ['renders', authToken],
		queryFn: async () => {
			return await getAllRenders(authToken);
		}
	});

	const placeholderItem = Array.from({ length: 100 });
</script>

<div class="flex w-full flex-col p-12">
	{#if $allRendersQuery.isPending}
		<div class="flex w-full justify-center py-8">
			<Spinner size="12" color="primary" />
			<span class="ml-2">Loading renders...</span>
		</div>
	{:else if $allRendersQuery.isError}
		<Alert color="red" class="w-full">
			<span class="font-medium">Error loading renders</span>
		</Alert>
	{:else if $allRendersQuery.isSuccess}
		<div class="flex w-full flex-wrap justify-center gap-4">
			{#each $allRendersQuery.data as render}
				<div class="w-80">
					<RenderPreviewCard {render} />
				</div>
			{/each}
			<div class="w-80">
				<NewRenderCard />
			</div>
		</div>
	{/if}
</div>

<!-- using Tailwind classes directly in HTML instead of CSS -->
