// ui/src/views/renders/RenderPreviewCard.tsx
import { Card, Progress, Spinner, type CardTheme } from 'flowbite-react';
import { Link } from 'react-router-dom';
import type { DeepPartial } from 'flowbite-react/types';
import { isRenderStateRunning, isRenderStatePausing, type Render } from '@/utils/api';
import { useLatestCheckpointImage } from '@/hooks/useLatestCheckpointImage';

export type RenderPreviewCardProps = {
  render: Render;
};

export function RenderPreviewCard(props: RenderPreviewCardProps) {
  const { render } = props;
  const checkpointImageQuery = useLatestCheckpointImage({ renderID: render.id });
  const renderSize = render.config.parameters.image_dimensions;
  const state = render.state;
  const running = isRenderStateRunning(state);
  const pausing = isRenderStatePausing(state);
  const showProgress = running || pausing;
  const progress = running
    ? state.running.progress_info.progress
    : pausing
      ? state.pausing.progress_info.progress
      : 0;

  const cardTheme: DeepPartial<CardTheme> = {
    root: {
      base: 'border-none bg-zinc-800 dark:bg-zinc-800',
      children: 'p-0',
    },
  };

  return (
    <Link to={`/renders/${render.id}`}>
      <Card
        className="text-zinc-200 hover:bg-zinc-700"
        theme={cardTheme}
        renderImage={() => (
          <div className="flex aspect-video items-center justify-center overflow-hidden bg-zinc-900">
            {checkpointImageQuery.isPending && (
              <div className="flex flex-col items-center justify-center">
                <Spinner size="xl" color="info" />
                <span className="mt-2 text-sm">loading preview...</span>
              </div>
            )}
            {checkpointImageQuery.isError && (
              <img
                src={`https://placehold.co/${renderSize[0]}x${renderSize[1]}?text=Error`}
                alt="Render Error"
                className="h-full w-full object-contain"
              />
            )}
            {checkpointImageQuery.isSuccess && (
              <img
                src={checkpointImageQuery.data}
                alt="Render Preview"
                className="h-full w-full object-contain"
              />
            )}
          </div>
        )}
      >
        <div className="min-h-1.5">
          {showProgress && (
            <Progress
              progress={Math.round(progress * 100)}
              color={running ? 'blue' : 'yellow'}
              size="sm"
              theme={{
                base: 'rounded-none',
                bar: 'rounded-none transition-[width] duration-1000 ease-linear',
              }}
            />
          )}
        </div>
        <div className="flex items-center justify-between p-3">
          <h5 className="text-lg font-semibold">{render.config.name}</h5>
          <code className="text-sm font-light italic">#{render.id}</code>
        </div>
      </Card>
    </Link>
  );
}

// ui/src/routes/renders/RenderPreviewCard.svelte
<script lang="ts">
	import { Card, Spinner } from 'flowbite-svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import { getToken } from '$lib/state/auth.svelte';
	import { getLatestCheckpointImage } from '$lib/utils/api';
	import type { Render } from '$lib/utils/api';

	type Props = {
		render: Render;
	};

	const { render }: Props = $props();

	const authToken = getToken();

	const checkpointImageURLQuery = createQuery({
		queryKey: ['latestCheckpoint', render.id, authToken],
		queryFn: async () => {
			return await getLatestCheckpointImage(authToken, render.id).then(
				(blob) => {
					return URL.createObjectURL(blob);
				}
			);
		}
	});
</script>

<Card
	href={`/renders/${render.id}`}
	class="!bg-zinc-800 !text-zinc-200 hover:!bg-zinc-700"
>
	<!-- card image section -->
	<div class="flex w-full items-center justify-center p-2">
		{#if $checkpointImageURLQuery.isPending}
			{@const renderSize = render.config.parameters.image_dimensions}
			<div class="flex flex-col items-center justify-center p-4">
				<Spinner size="8" color="primary" />
				<span class="mt-2 text-sm">loading preview...</span>
			</div>
		{:else if $checkpointImageURLQuery.isError}
			{@const renderSize = render.config.parameters.image_dimensions}
			<img
				src="https://placehold.co/{renderSize[0]}x{renderSize[1]}?text=Error"
				alt="Render Error"
				class="max-h-48 w-full object-scale-down"
			/>
		{:else if $checkpointImageURLQuery.isSuccess}
			<img
				src={$checkpointImageURLQuery.data}
				alt="Render Preview"
				class="max-h-48 w-full object-scale-down"
			/>
		{/if}
	</div>

	<!-- card header section -->
	<div class="flex items-baseline justify-between border-t p-3">
		<h5 class="text-lg font-semibold">
			{render.id}
		</h5>
		<code class="text-sm font-light italic">
			{render.config.name}
		</code>
	</div>
</Card>

<!-- using Tailwind classes directly in HTML instead of CSS -->
