// ui/src/views/renders/new/index.tsx
import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useStore } from '@tanstack/react-form';

import {
  Sidebar,
  SidebarItems,
  SidebarItemGroup,
  Spinner,
  Button,
  type SidebarTheme,
} from 'flowbite-react';
import { Separator } from '@/components/Separator';
import type { DeepPartial } from 'flowbite-react/types';
import { Controls } from './Controls';
import { Scene } from './Scene';
import { useAuth } from '@/providers/auth';
import { postRender } from '@/utils/api';
import { useRenderForm } from '@/hooks/useRenderForm';

export function NewRenderPage() {
  const navigate = useNavigate();
  const { user, mustGetToken } = useAuth();
  const token = mustGetToken();

  const [isCreatingRender, setIsCreatingRender] = useState(false);

  // canvas container sizing
  const containerRef = useRef<HTMLDivElement>(null);
  const [containerWidth, setContainerWidth] = useState(0);
  const [containerHeight, setContainerHeight] = useState(0);

  // ResizeObserver for canvas container
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    const observer = new ResizeObserver((entries) => {
      const { width, height } = entries[0].contentRect;
      setContainerWidth(width);
      setContainerHeight(height);
    });
    observer.observe(container);
    return () => observer.disconnect();
  }, []);

  const form = useRenderForm({ user });

  // canvas sizing - maintain aspect ratio in container
  const imageDimensions = useStore(form.store, (state) => state.values.parameters.image_dimensions);
  const aspectRatio = imageDimensions[0] / imageDimensions[1];
  const formValuesForSubmit = useStore(form.store, (state) => state.values);

  let canvasWidth = 0;
  let canvasHeight = 0;
  if (containerWidth > 0 && containerHeight > 0) {
    const containerAspectRatio = containerWidth / containerHeight;
    if (containerAspectRatio > aspectRatio) {
      canvasHeight = containerHeight;
      canvasWidth = containerHeight * aspectRatio;
    } else {
      canvasWidth = containerWidth;
      canvasHeight = containerWidth / aspectRatio;
    }
  }

  async function handleCreateRender() {
    setIsCreatingRender(true);
    try {
      const response = await postRender(token, formValuesForSubmit);
      navigate(`/renders/${response.id}`);
    } catch {
      setIsCreatingRender(false);
    }
  }
  function handleDownloadConfig() {
    const json = JSON.stringify(formValuesForSubmit, null, 2);

    const blob = new Blob([json], {
      type: 'application/json',
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = 'render-config.json';
    
document.body.appendChild(link);
link.click();
document.body.removeChild(link);
  }
  const sidebarTheme: DeepPartial<SidebarTheme> = {
    root: {
      base: 'bg-zinc-900 dark:bg-zinc-900',
      inner: 'bg-zinc-900 dark:bg-zinc-900',
    },
  };

  return (
    <div className="flex h-full w-full">
      <Sidebar theme={sidebarTheme} className="z-10 h-full w-lg">
        <SidebarItems className="h-full">
          <SidebarItemGroup className="flex h-full flex-col">
            <div className="mb-0 flex flex-1 flex-col gap-2 overflow-y-auto">
              <Controls form={form} />
            </div>
            <div className="mt-0 flex flex-col gap-2">
              <Separator className="mt-0" />
              <Button color="gray" onClick={handleDownloadConfig}>
                Download Config
              </Button>
              <Button onClick={handleCreateRender} disabled={isCreatingRender} color="default">
                {isCreatingRender ? (
                  <span className="flex items-center justify-center gap-2">
                    <Spinner size="sm" color="info" />
                    Creating...
                  </span>
                ) : (
                  'Create Render'
                )}
              </Button>
            </div>
          </SidebarItemGroup>
        </SidebarItems>
      </Sidebar>

      <div ref={containerRef} className="m-8 flex flex-1 items-center justify-center">
        <div
          style={{ width: canvasWidth, height: canvasHeight }}
          className="box-border border border-zinc-500"
        >
          {canvasWidth > 0 && canvasHeight > 0 && <Scene form={form} />}
        </div>
      </div>
    </div>
  );
}

// ui/src/routes/renders/new/+page.svelte
<script lang="ts">
	import { Canvas } from '@threlte/core';
	import Scene from './Scene.svelte';
	import { getDefaultRenderConfig } from '$lib/utils/render';
	import { setContext } from 'svelte';
	import { postRender } from '$lib/utils/api';
	import { getToken } from '$lib/state/auth.svelte';
	import { goto } from '$app/navigation';
	import Controls from './Controls.svelte';
	import { Sidebar, Button, Progressradial, Spinner } from 'flowbite-svelte';

	const authToken = getToken();

	// store state
	const renderConfig = $state(getDefaultRenderConfig());
	setContext('renderConfig', renderConfig);

	let aspectRatio = $derived(
		renderConfig.parameters.image_dimensions[0] /
			renderConfig.parameters.image_dimensions[1]
	);

	// track container dimensions
	let containerWidth = $state(0);
	let containerHeight = $state(0);

	// calculate canvas dimensions
	const canvasSize = $derived.by(() => {
		// if container isn't measured yet, return zeros
		if (!containerWidth || !containerHeight) return [0, 0];

		// calculate dimensions that fit in container while preserving aspect ratio
		const containerAspectRatio = containerWidth / containerHeight;

		if (containerAspectRatio > aspectRatio) {
			// container is wider than desired ratio, so height is limiting factor
			return [containerHeight * aspectRatio, containerHeight];
		} else {
			// container is taller than desired ratio, so width is limiting factor
			return [containerWidth, containerWidth / aspectRatio];
		}
	});

	let isCreatingRender = $state(false);

	async function handleCreateRender() {
		isCreatingRender = true;

		postRender(authToken, renderConfig)
			.then((response) => {
				isCreatingRender = false;
				goto(`/renders/${response.id}`);
			})
			.catch(() => {
				isCreatingRender = false;
			});
	}
</script>

<div class="flex h-full max-h-[calc(100vh-4rem)] w-full flex-1">
	<Sidebar
		divClass="!bg-inherit h-full"
		alwaysOpen
		position="static"
		class="w-128 z-10 !bg-zinc-900"
	>
		<div class="flex h-full flex-col items-stretch gap-2">
			<Controls {renderConfig} />
			<Button
				onclick={() => {
					handleCreateRender();
				}}
				disabled={isCreatingRender}
				class="mt-auto"
			>
				{#if isCreatingRender}
					<Spinner size="4" />
				{:else}
					Create Render
				{/if}
			</Button>
		</div>
	</Sidebar>
	<div
		class="m-8 flex flex-1 items-center justify-center"
		bind:clientWidth={containerWidth}
		bind:clientHeight={containerHeight}
	>
		<div
			style="width: {canvasSize[0]}px; height: {canvasSize[1]}px;"
			class="box-sizing border-1 border-zinc-500"
		>
			<Canvas>
				<Scene />
			</Canvas>
		</div>
	</div>
</div>
