// ui-react/src/views/new-render/GeometricControlsCard.tsx
import { useState } from 'react';
import { Card, Button } from 'flowbite-react';
import { ChevronDownIcon, ChevronUpIcon } from 'flowbite-react';
import Separator from '../../components/Separator';
import NestedGeometricHeader from './NestedGeometricHeader';
import TextArrayInputControl from '../../components/ui/TextArrayInputControl';
import RangeControl from '../../components/ui/RangeControl';
import SelectControl from '../../components/ui/SelectControl';
import { getGeometricData, getGeometricDataSafe } from '../../utils/render/geometric';
import { fixReferences } from '../../utils/render/utils';
import type { RenderConfig } from '../../utils/render/config';

function TrashIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
    </svg>
  );
}

function DeleteGeometricButton({ onClick }: { onClick: () => void }) {
  return (
    <div className="flex w-full justify-end">
      <Button color="failure" onClick={onClick} size="sm">
        <TrashIcon className="h-5 w-5" />
      </Button>
    </div>
  );
}

function GeometricMaterialSelect({
  form,
  name,
  items,
}: {
  form: any;
  name: string;
  items: { name: string; value: string }[];
}) {
  return (
    <SelectControl
      form={form}
      field={`geometrics.${name}.material`}
      label="Material"
      items={items}
    />
  );
}

interface GeometricControlsCardProps {
  form: any;
  geometricName: string;
}

export default function GeometricControlsCard({
  form,
  geometricName,
}: GeometricControlsCardProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const renderConfig = form.state.values as RenderConfig;

  const { data: geometricData } = getGeometricDataSafe(renderConfig, geometricName);

  function handleDeleteGeometric(name: string) {
    const newGeometrics = { ...renderConfig.geometrics };
    delete newGeometrics[name];

    const newConfig: RenderConfig = {
      ...renderConfig,
      geometrics: newGeometrics,
    };

    const fixed = fixReferences(newConfig);
    form.setFieldValue('geometrics', fixed.geometrics);
    form.setFieldValue('scenes', fixed.scenes);
    form.setFieldValue('materials', fixed.materials);
    form.setFieldValue('textures', fixed.textures);
  }

  // Build material select items
  const materialItems = Object.keys(renderConfig.materials ?? {}).map((key) => ({
    name: key,
    value: key,
  }));

  // Controls for a specific geometric type
  function renderControls(name: string) {
    const { data } = getGeometricData(renderConfig, name);

    switch (data.type) {
      case 'box':
        return (
          <>
            <TextArrayInputControl form={form} field={`geometrics.${name}.a`} label="Corner 1" valueLabels={['x', 'y', 'z']} type="number" />
            <TextArrayInputControl form={form} field={`geometrics.${name}.b`} label="Corner 2" valueLabels={['x', 'y', 'z']} type="number" />
            <GeometricMaterialSelect form={form} name={name} items={materialItems} />
          </>
        );
      case 'list':
        return (
          <>
            {(data as any).geometrics.map((subName: string, i: number) => (
              <div key={subName}>
                {i > 0 && <Separator />}
                <NestedGeometricHeader geometricName={subName} renderConfig={renderConfig} />
                {renderControls(subName)}
              </div>
            ))}
          </>
        );
      case 'rotate_x':
      case 'rotate_y':
      case 'rotate_z': {
        const rotateData = data as any;
        const hasDegrees = 'degrees' in rotateData;
        return (
          <>
            <RangeControl
              form={form}
              field={`geometrics.${name}.${hasDegrees ? 'degrees' : 'radians'}`}
              label={hasDegrees ? 'Degrees of Rotation' : 'Radians of Rotation'}
              min={0}
              max={hasDegrees ? 360 : 2 * Math.PI}
              step={hasDegrees ? 1.0 : 0.01}
            />
            <Separator />
            <NestedGeometricHeader geometricName={rotateData.geometric} renderConfig={renderConfig} />
            {renderControls(rotateData.geometric)}
          </>
        );
      }
      case 'translate': {
        const transData = data as any;
        return (
          <>
            <NestedGeometricHeader geometricName={transData.geometric} renderConfig={renderConfig} />
            {renderControls(transData.geometric)}
          </>
        );
      }
      case 'parallelogram':
        return (
          <>
            <TextArrayInputControl form={form} field={`geometrics.${name}.lower_left`} label="Lower Left" valueLabels={['x', 'y', 'z']} type="number" />
            <TextArrayInputControl form={form} field={`geometrics.${name}.u`} valueLabels={['x', 'y', 'z']} type="number" label="<em>u</em> Vector" />
            <TextArrayInputControl form={form} field={`geometrics.${name}.v`} valueLabels={['x', 'y', 'z']} type="number" label="<em>v</em> Vector" />
            <GeometricMaterialSelect form={form} name={name} items={materialItems} />
          </>
        );
      case 'sphere':
        return (
          <>
            <TextArrayInputControl form={form} field={`geometrics.${name}.center`} label="Center" valueLabels={['x', 'y', 'z']} type="number" />
            <TextInputControl form={form} field={`geometrics.${name}.radius`} label="Radius" valueLabel="radius" type="number" />
            <GeometricMaterialSelect form={form} name={name} items={materialItems} />
          </>
        );
      case 'triangle':
        return (
          <>
            <TextArrayInputControl form={form} field={`geometrics.${name}.a`} label="Point A" valueLabels={['x', 'y', 'z']} type="number" />
            <TextArrayInputControl form={form} field={`geometrics.${name}.b`} label="Point B" valueLabels={['x', 'y', 'z']} type="number" />
            <TextArrayInputControl form={form} field={`geometrics.${name}.c`} label="Point C" valueLabels={['x', 'y', 'z']} type="number" />
            <GeometricMaterialSelect form={form} name={name} items={materialItems} />
          </>
        );
      default:
        return <h6 className="text-sm">Unknown or unimplemented geometric: {data.type}</h6>;
    }
  }

  return (
    <Card className="flex max-w-full flex-col !bg-zinc-800 !text-zinc-200">
      <button
        type="button"
        className="flex items-center justify-between p-4 pr-2"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <h2 className="text-xl font-bold">{geometricName}</h2>
        <div className="flex flex-row items-center gap-2">
          <h3 className="text-lg font-light italic">{geometricData.type}</h3>
          {isExpanded ? (
            <ChevronUpIcon className="h-8 w-auto" />
          ) : (
            <ChevronDownIcon className="h-8 w-auto" />
          )}
        </div>
      </button>
      {isExpanded && (
        <div>
          <Separator />
          <div className="flex w-full flex-col gap-2 p-4">
            {renderControls(geometricName)}
            <DeleteGeometricButton onClick={() => handleDeleteGeometric(geometricName)} />
          </div>
        </div>
      )}
    </Card>
  );
}

// ui/src/routes/renders/new/GeometricControlsCard.svelte
<script lang="ts">
	import NestedGeometricHeader from './NestedGeometricHeader.svelte';
	import RangeControl from '$lib/RangeControl.svelte';
	import Separator from '$lib/Separator.svelte';
	import {
		getGeometricData,
		type GeometricBox,
		type GeometricData,
		type GeometricInstanceRotate,
		type GeometricList,
		type GeometricParallelogram,
		type RenderConfig
	} from '$lib/utils/render';
	import VectorInputControl from '$lib/VectorInputControl.svelte';
	import { Card, Heading } from 'flowbite-svelte';
	import { ChevronDownOutline, ChevronUpOutline } from 'flowbite-svelte-icons';
	import { slide } from 'svelte/transition';
	import { getContext } from 'svelte';

	type Props = {
		geometric: string | GeometricData;
	};

	const { geometric }: Props = $props();

	const renderConfig = getContext<RenderConfig>('renderConfig');

	const geometricData = getGeometricData(renderConfig, geometric);

	let isExpanded = $state(false);
	function handleToggleExpandCard() {
		isExpanded = !isExpanded;
	}
</script>

{#snippet controlsSubGeometric(data: string | GeometricData)}
	{@const geometricData = getGeometricData(renderConfig, data)}

	<NestedGeometricHeader {data} />
	{@render controlsGeometric(geometricData)}
{/snippet}

{#snippet controlsGeometric(data: GeometricData)}
	{#if data.type === 'box'}
		{@render controlsGeometricBox(data)}
	{:else if data.type === 'list'}
		{@render controlsGeometricList(data)}
	{:else if data.type === 'rotate_x' || data.type === 'rotate_y' || data.type === 'rotate_z'}
		{@render controlsGeometricRotate(data)}
	{:else if data.type === 'parallelogram'}
		{@render controlsGeometricParallelogram(data)}
	{:else}
		<Heading tag="h6" class="text-sm"
			>Unknown geometric! (or not yet implemented...)</Heading
		>
	{/if}
{/snippet}

{#snippet controlsGeometricBox(data: GeometricBox)}
	<VectorInputControl
		label="Corner 1"
		bind:values={data.a}
		valueLabels={['X', 'Y', 'Z']}
	/>
	<VectorInputControl
		label="Corner 2"
		bind:values={data.b}
		valueLabels={['X', 'Y', 'Z']}
	/>
{/snippet}

{#snippet controlsGeometricList(data: GeometricList)}
	{#each data.geometrics as subGeometric, index}
		{#if index > 0}
			<Separator />
		{/if}
		{@render controlsSubGeometric(subGeometric)}
	{/each}
{/snippet}

{#snippet controlsGeometricRotate(data: GeometricInstanceRotate)}
	{#if 'degrees' in data}
		<RangeControl
			label="Degrees of Rotation"
			bind:value={data.degrees}
			min={0.0}
			max={360.0}
			step={1.0}
		/>
	{:else}
		<RangeControl
			label="Radians of Rotation"
			bind:value={data.radians}
			min={0.0}
			max={2 * Math.PI}
			step={0.01}
		/>
	{/if}
	<Separator />
	{@render controlsSubGeometric(data.geometric)}
{/snippet}

{#snippet controlsGeometricParallelogram(data: GeometricParallelogram)}
	<VectorInputControl
		label="Lower Left"
		bind:values={data.lower_left}
		valueLabels={['X', 'Y', 'Z']}
	/>
	<VectorInputControl bind:values={data.u} valueLabels={['X', 'Y', 'Z']}>
		{#snippet label()}
			<em>u</em> Vector
		{/snippet}
	</VectorInputControl>
	<VectorInputControl bind:values={data.v} valueLabels={['X', 'Y', 'Z']}>
		{#snippet label()}
			<em>v</em> Vector
		{/snippet}
	</VectorInputControl>
{/snippet}

<Card class="flex max-w-full flex-col !bg-zinc-800 !text-zinc-200">
	<button
		class="flex items-center justify-between p-4 pr-2"
		onclick={() => handleToggleExpandCard()}
	>
		{#if typeof geometric === 'string'}
			<Heading tag="h2" class="text-xl font-bold">
				{geometric}
			</Heading>
		{:else}
			<Heading tag="h2" class="text-xl font-light italic">inline</Heading>
		{/if}
		<div class="flex flex-row">
			<Heading tag="h3" class="text-lg font-light italic">
				{geometricData.type}
			</Heading>
			{#if isExpanded}
				<ChevronUpOutline class="h-8 w-auto" />
			{:else}
				<ChevronDownOutline class="h-8 w-auto" />
			{/if}
		</div>
	</button>
	{#if isExpanded}
		<div transition:slide={{ duration: 300 }}>
			<Separator />
			<div class="flex flex-col gap-2 p-4">
				<!-- controls -->
				{@render controlsGeometric(geometricData)}
			</div>
		</div>
	{/if}
</Card>
