// ui-react/src/views/new-render/NestedGeometricHeader.tsx
import Separator from '../../components/Separator';
import { getGeometricData } from '../../utils/render/geometric';
import type { RenderConfig } from '../../utils/render/config';

interface NestedGeometricHeaderProps {
  geometricName: string;
  renderConfig: RenderConfig;
}

export default function NestedGeometricHeader({
  geometricName,
  renderConfig,
}: NestedGeometricHeaderProps) {
  const { data } = getGeometricData(renderConfig, geometricName);

  return (
    <div className="flex justify-between">
      <h2 className="text-lg font-bold italic">Contained Geometric</h2>
      <div className="flex gap-2">
        <h3 className="text-lg font-light not-italic">{geometricName}</h3>
        <Separator vertical />
        <h3 className="text-lg font-light italic">{data.type}</h3>
      </div>
    </div>
  );
}

// ui/src/routes/renders/new/NestedGeometricHeader.svelte
<script lang="ts">
	import { Heading } from 'flowbite-svelte';
	import Separator from '$lib/Separator.svelte';
	import {
		getGeometricData,
		type GeometricData,
		type RenderConfig
	} from '$lib/utils/render';
	import { getContext } from 'svelte';

	type Props = {
		data: string | GeometricData;
	};

	const { data }: Props = $props();

	const renderConfig = getContext<RenderConfig>('renderConfig');

	const { type: geometricType } = getGeometricData(renderConfig, data);
</script>

<div class="flex justify-between">
	<Heading tag="h2" class="text-lg font-bold italic"
		>Contained Geometric</Heading
	>
	<div class="flex gap-2">
		{#if typeof data === 'string'}
			<Heading tag="h3" class="text-lg font-light not-italic">{data}</Heading>
		{:else}
			<Heading tag="h3" class="text-lg font-light italic">inline</Heading>
		{/if}
		<Separator vertical />
		<Heading tag="h3" class="text-lg font-light italic">{geometricType}</Heading
		>
	</div>
</div>
