// ui-svelte/src/routes/(authenticated)/renders/new/NewMaterialSpeedDial.svelte
<script lang="ts">
	import { RenderConfigSchema } from '$lib/utils/render/config';
	import {
		defaultMaterialForType,
		type MaterialData
	} from '$lib/utils/render/material';
	import { capitalize, getNextUniqueName } from '$lib/utils/render/utils';
	import {
		Listgroup,
		ListgroupItem,
		SpeedDial,
		SpeedDialTrigger,
		Tooltip
	} from 'flowbite-svelte';
	import { PlusOutline } from 'flowbite-svelte-icons';
	import { type SuperForm } from 'sveltekit-superforms';
	import { z } from 'zod';

	const schema = RenderConfigSchema;
	type Props = {
		superform: SuperForm<z.infer<typeof schema>>;
	};

	const { superform }: Props = $props();
	const { form } = $derived(superform);

	function handleNewMaterial(
		type: Exclude<MaterialData['type'], 'dielectric'>
	) {
		const newMaterials = defaultMaterialForType(type);
		const nextName = getNextUniqueName(
			$form.materials,
			`New ${capitalize(type)}`
		);

		$form.materials[nextName] = newMaterials;
	}
</script>

<SpeedDialTrigger transition={undefined}>
	{#snippet icon()}
		<PlusOutline size="xl" />
	{/snippet}
</SpeedDialTrigger>
<SpeedDial placement="top-end">
	<Listgroup active>
		<ListgroupItem
			disabled
			class="flex"
			onclick={() => {
				console.warn('dielectric material not implemented yet');
				// TODO: implement dielectric material
				// handleNewMaterial('dielectric')
			}}
		>
			<PlusOutline size="md" class="me-2" />
			Dielectric Material
		</ListgroupItem>
		<Tooltip><span>Dielectric Materials are not yet implemented</span></Tooltip>
		<ListgroupItem onclick={() => handleNewMaterial('lambertian')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Lambertian Material
		</ListgroupItem>
		<ListgroupItem onclick={() => handleNewMaterial('specular')} class="flex">
			<PlusOutline size="md" class="me-2" />
			Specular Material
		</ListgroupItem>
	</Listgroup>
</SpeedDial>

// ui/src/views/renders/new/Controls/NewMaterialSpeedDial.tsx
import { Dropdown, DropdownItem } from 'flowbite-react';
import { defaultMaterialForType, type MaterialData } from '@/utils/render/material';
import { capitalize, getNextUniqueName } from '@/utils/render/utils';
import type { RenderForm } from '@/hooks/useRenderForm';
import { useSelector } from '@tanstack/react-store';
import { HiPlus } from 'react-icons/hi2';

type MaterialType = Exclude<MaterialData['type'], 'dielectric'>;

interface NewMaterialSpeedDialProps {
  form: RenderForm;
}

export function NewMaterialSpeedDial(props: NewMaterialSpeedDialProps) {
  const { form } = props;

  const formValues = useSelector(form.store, (state) => state.values);

  function handleNewMaterial(type: MaterialType) {
    const newMaterial = defaultMaterialForType(type);
    const nextName = getNextUniqueName(formValues.materials ?? {}, `New ${capitalize(type)}`);

    form.setFieldValue('materials', {
      ...formValues.materials,
      [nextName]: newMaterial,
    });
  }

  return (
    <Dropdown label={<HiPlus className="h-6 w-6" />} arrowIcon={false} color="light" size="sm">
      <DropdownItem disabled>
        <div className="flex items-center gap-2">
          <HiPlus className="h-4 w-4" />
          Dielectric Material
        </div>
      </DropdownItem>
      <DropdownItem onClick={() => handleNewMaterial('lambertian')}>
        <div className="flex items-center gap-2">
          <HiPlus className="h-4 w-4" />
          Lambertian Material
        </div>
      </DropdownItem>
      <DropdownItem onClick={() => handleNewMaterial('specular')}>
        <div className="flex items-center gap-2">
          <HiPlus className="h-4 w-4" />
          Specular Material
        </div>
      </DropdownItem>
    </Dropdown>
  );
}
